import { type NextRequest, NextResponse } from "next/server";
import { isAxiosError } from "axios";
import { api } from "../api";
import { logErrorResponse } from "../_utils/utils";

export const runtime = "nodejs";

function createUpstreamHeaders(request: NextRequest): Headers {
  const headers = new Headers();
  const contentType = request.headers.get("content-type");
  const cookie = request.headers.get("cookie");
  const accept = request.headers.get("accept");

  // Preserve the multipart boundary generated by the browser.
  if (contentType) headers.set("content-type", contentType);
  if (cookie) headers.set("cookie", cookie);
  if (accept) headers.set("accept", accept);

  return headers;
}

export async function GET(request: NextRequest) {
  try {
    const page = request.nextUrl.searchParams.get("page") ?? "1";
    const limit = request.nextUrl.searchParams.get("limit") ?? "6";
    const filter = request.nextUrl.searchParams.get("filter");

    const params: Record<string, string> = { page, limit };
    if (filter) {
      params.filter = filter;
    }

    const res = await api.get("/articles", { params });

    return NextResponse.json(res.data, { status: res.status });
  } catch (error) {
    if (isAxiosError(error)) {
      logErrorResponse(error.response?.data);
      return NextResponse.json(
        {
          message:
            error.response?.data?.message ?? "Failed to load articles",
        },
        { status: error.response?.status ?? 500 },
      );
    }

    logErrorResponse({ message: (error as Error).message });
    return NextResponse.json(
      { message: "Internal Server Error" },
      { status: 500 },
    );
  }
}

export async function POST(request: NextRequest) {
  const backendUrl = process.env.BACKEND_URL?.replace(/\/+$/, "");

  if (!backendUrl) {
    return NextResponse.json(
      { message: "Article service is not configured" },
      { status: 500 },
    );
  }

  try {
    const body = await request.arrayBuffer();
    const upstream = await fetch(`${backendUrl}/articles`, {
      method: "POST",
      headers: createUpstreamHeaders(request),
      body,
      cache: "no-store",
    });

    const headers = new Headers();
    const contentType = upstream.headers.get("content-type");

    if (contentType) headers.set("content-type", contentType);

    return new NextResponse(upstream.body, {
      status: upstream.status,
      statusText: upstream.statusText,
      headers,
    });
  } catch (error) {
    console.error("Failed to proxy article creation", error);

    return NextResponse.json(
      { message: "Failed to publish article" },
      { status: 502 },
    );
  }
}
